### ISSUE TITLE
Error: Output refers to sensitive values

### ISSUE THREAD

**Issue by dwschulze** [stormic-nomad-nishant/cloud_native_azure#2]
Running `terraform apply` in cloud_native_azure/Chapter2/1.2.1.4/A_blob_storage_account give the following error:

```
│ Error: Output refers to sensitive values
│ 
│   on output.tf line 9:
│    9: output "Primary-Access-Key" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root
│ module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true

```

If I add
`  sensitive = true`

to output.tf it runs but shows

`Primary-Access-Key = <sensitive>`

But I need the Primary-Access-Key value.

**Comment by stormic-nomad-nishant** [comment]
Since you have marked an output value as sensitive in Terraform by adding` sensitive = true,` it means that the value will be obfuscated and not displayed in the output. This is a security measure to prevent sensitive data from being unintentionally exposed.

Suppose you need to retrieve the Primary-Access-Key value while still marking it as sensitive. In that case, you can use the value within your Terraform configuration to perform any necessary operations or resource creation. ** However, keep in mind that the value will not be displayed directly in the Terraform output.**{This is probably a secure design feature}  


You can though do `terraform output Primary-Access-Key` to view the secret. More at https://developer.hashicorp.com/terraform/tutorials/configuration-language/outputs#redact-sensitive-outputs
